### ISSUE TITLE
Review #1 - Detalles en el ingreso de sala

### ISSUE THREAD

**Issue by FacundoEG** [LksR-dev/piedras-papel-tijeras-online#1]
Hola Lucas! como andas querido? primero que todo te queria felicitar por haber enviado el desafío final del mod 6!

Mira te comento, estoy revisando el desafío y dentro de todo se ve muy bien, encuentro un solo error que es una premisa del desafío que tengo que señalarte y pedirte que revises:

Fijate que en el desafío se pide que no puedan ingresar mas de dos usuarios a una sala, ya que al tener dos usuarios conectados se considera "llena". 

![image](https://user-images.githubusercontent.com/79592789/174495916-7b149610-5d14-422d-9a55-e84771d6aaff.png)

Probe eso en tu desafío y me permite ingresar mas de dos jugadores, a lo que cuando vas a jugar se rompe y pierde el sentido de la jugabilidad:

![image](https://user-images.githubusercontent.com/79592789/174495811-a04a1fae-00d7-49e9-a1b0-2e3e3b091611.png)
![image](https://user-images.githubusercontent.com/79592789/174495827-9c2eacd2-169c-4cd7-8874-a5679d6f9be7.png)

Te tendría que pedir que revises eso y ya te lo puedo dejar como aprobado al desafío.

Despues por el resto se ve todo muy bien! la jugabilidad es fluida y el front esta bien implementado tanto en mobile como desktop.

Así que de mi parte esperamos esos cambios y dale que te falta nada! abrazo!

**Comment by LksR-dev** [comment]
Hola Facu! Como estas? En primer lugar agradecerte por dedicarle el tiempo de ver la aplicacion y testearla.

Estuve viendo lo que me decis y creo haberlo arreglado, si bien al ingresar un tercer participante no te lleva a una page como la que me mostraste, si tira un mensaje en pantalla y no permite que se avance de pagina.

Mil gracias por toda la ayuda y aguante como siempre! Abrazo Facu, que andes bien.

**Comment by FacundoEG** [comment]
Listo Lukis, ahi revise todo y funciona de 10 tu implementación.

Te dejo mi LGTM y te deseo lo mejor para el proximo modulo, a romperla!
